= Architecture Examples
// Copyright 2017 NEOautus Ltd. (http://neoautus.com)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

This is the source code for the architectural examples cited on https://github.com/neoautus/lucidj-docs/blob/master/docs/README.adoc[LucidJ Documentation].

IMPORTANT: *Please be sure to check the documentation inside every subproject (the numerated directories). Every subproject have it's own documentation and _instructions to build and run the tests._*

== Prerequisites for Building

* Java Development Kit 8 or later
* Ant (minimun Ant 1.8.0)

== Before Starting

The examples were built to illustrate both functionality and implementation. They are IDE-agnostic, showing all the steps to build an OSGi application from zero without need of a particular combination of IDE and plugin or any wizzard tool.

We achieve this using Ant. Today, you can also use Maven to build any OSGi project, however Maven is magical in it's own way, because there are many predefined (and sane) defaults. You may choose Maven for your own projects. On the other side, Ant allows you to follow the logic of building an OSGi jar file, with all required steps very visible. We strongly suggest you to take a time to look into `build.xml` and `configure.xml` to get a good idea of whats going on, and how things are being done. It may look intimidating at first, but hopefully will also be instructive.

Specially, you will get known to `Bnd` (http://bndtools.org/), which is *the* reference tool to build all OSGi-related stuff you can imagine. There's also the iPojo processor, which manipulates the code after compilation and demonstrates the post-processing of OSGi jar bundles.

=== Building

You need a _stage_ to work. Our default _stage_ is built with Apache Felix. The stage area is where the bundles will be deployed, and every subproject will deploy it's artifacts there. You may also build an alternative stage using Apache Karaf if you wish:

* https://github.com/neoautus/architecture-examples/tree/master/stage-templates/apache-felix-5.6[Build the Felix stage]: Follow these instructions to build the _default_ Felix stage;
+
or

* https://github.com/neoautus/architecture-examples/tree/master/stage-templates/apache-karaf-4.1/[Build the Karaf stage]: Use these instructions to build an _alternative_ Karaf stage.

To specific instructions to run the examples and the tests are available for each subproject on the `README.adoc` file.

To build _all_ subprojects at once, just type `ant` on project root.

By default, Ant will download and cache all needed tools, then invoke the `build-all` target. The output of all builds will be located in `dist/` directory beneath every subproject. If the stage is available, all built bundles will be automatically copied into `stage/deploy`.

=== Running

To run the OSGi container available on the `stage/` directory use:

* Run `stage/bin/felix` for Apache Felix (our default container);
+
or

* Run `stage/bin/karaf` for a Apache Karaf stage.

=== Administration and Monitoring

There are 2 administration tools available:

* http://felix.apache.org/documentation/subprojects/apache-felix-web-console.html[Apache Felix Web Console^]: The built-in admin console available for Apache Felix. http://localhost:6502/system/console[Click here to open Felix Console at http://localhost:6502/system/console/]. Both username and password are `admin`.
* http://hawt.io[Hawt.io Console^]: Additional web console. Open source, extendable with lots of plugins. Use Ant to launch the Hawt.io server running `ant run-hawtio` on project root. After started, http://localhost:8080/hawtio/[click here to open Hawt.io Console at http://localhost:8181/hawtio/]. On the connection dialog that follows, be sure to set _host_ to `localhost` and _port_ to `6502` (our default Felix host and port). Keep the default _path_ the same `jolokia`. We use https://jolokia.org/[Jolokia] to provide JMX over HTTP/JSON.

=== Useful Ant targets

For details on building the code, see `ant -p`.

These are the available targets:

* `ant build-stage`: build the stage with Apache Felix ready to run the examples;
* `ant build-karaf`: build the stage using Apache Karaf instead;
* `ant build-library-version`: build the Library Versioning subproject;
* `ant build-private-libraries`: build the Private Libraries subproject;
* `ant build-rest-playground`: build the Rest Playground subproject;
* `ant build-all`: builds all available subprojects;
* `ant run-hawtio`: download and start Hawt.io Web Console;
* `ant clean`: removes the `build` and `dist` directories;
* `ant zero`: same as `clean`, but also removes the `cache` directory with all downloaded tools;
* `ant configure`: rebuild the library and tools cache.

== Key Directories and Files

Important directories to be aware of:

* `cache` - stores the downloaded jars, custom tasks and other tools;
* `stage` - the local Apache Karaf installation built to test the subprojects.

The `configure.xml` file contains all the macros and targets used by the subprojects and it's worth looking. It can be used standalone on another projects.

== Installing Java on Raspberry Pi

Raspberry Pi have a fully certified OpenJDK distribution available: https://www.azul.com/products/zulu-embedded/[Zulu® Embedded^], built by https://www.azul.com/[Azul Systems^]. You can install it on Raspbian Stretch using:

....
# apt-get install dirmngr
# apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x219BD9C9
# echo 'deb http://repos.azulsystems.com/debian stable main' > /etc/apt/sources.list.d/zulu.list
# apt-get update
# apt-get install zulu-embedded-8
# java -version
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)
....

== Important Resources

If you need further information, please refer to the following resources:

* http://njbartlett.name/osgibook.html[OSGi in Practice^]: Free, Creative Commons-licensed book on OSGi by Neil Bartlett.
* https://www.osgi.org/developer/resources/learning-resources-tutorials/tutorial-archive/[Tutorial Archive from OSGi Alliance^]: Lots of great articles and resources.
* http://bndtools.org/[BND Tools^]: The standard OSGi tool to build artifacts.
* https://www.osgi.org/developer/specifications/[OSGi Specifications^]: All OSGi specifications available from OSGi Alliance.
* https://www.osgi.org/osgi-release-5-javadoc/[OSGi Release 5 Javadoc^]: Browse online the javadocs for OSGi R5 APIs.

== Copyright

This work is licensed under a http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0].
