= Architecture Examples
// Copyright 2017 NEOautus Ltd. (http://neoautus.com)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

This is the source code for the architectural examples cited on https://github.com/neoautus/lucidj-docs/blob/master/docs/README.adoc[LucidJ Documentation].

IMPORTANT: *Please be sure to check the documentation inside every subproject (the numerated directories). Every subdirectory have it's own instructions, `build.xml` and can be built independently.*

== Prerequisites for Building

* Java Development Kit 8 or later
* Ant (minimun Ant 1.8.0)

== Before Starting

The examples were built to illustrate both functionality and implementation. They are IDE-agnostic, showing all the steps to build an OSGi application from zero without need of a particular combination of IDE and plugin or any wizzard tool.

We achieve this using Ant. Today, you can also use Maven to build any OSGi project, however Maven is magical in it's own way, because there are many predefined (and sane) defaults. You may choose Maven for your own projects. On the other side, Ant allows you to follow the logic of building an OSGi jar file, with all required steps very visible. We strongly suggest you to take a time to look into build.xml and configure.xml to get a good idea of whats going on, and how things are being done. It may look intimidating at first, but hopefully will also be instructive.

Specially, you will get known to Bnd (http://bndtools.org/), which is *the* reference tool to build all OSGi-related stuff you can imagine. There's also the iPojo processor, which manipulates the code after compilation and demonstrates the post-processing of OSGi jar bundles.

=== Building

*This project can download and create a local install of Apache Karaf for you.* If you want to use the integrated Karaf, you can follow https://github.com/neoautus/architecture-examples/tree/master/00-stage-karaf[these instructions to build the Karaf stage].

To build _all_ subprojects at once, just type `ant` on project root.

By default, Ant will download and cache all needed tools, then invoke the `build-all` target. The output of all builds will be located in `dist/` directory beneath every subproject. If you're using the Karaf stage, all bundles will also be deployed into Karaf.

=== Useful Ant targets

For details on building the code, see `ant -p`.

These are the available targets:

* `ant build-stage`: build the stage with Apache Karaf ready to run the examples
* `ant build-library-version`: build the Library Versioning subproject;
* `ant build-private-libraries`: build the Private Libraries subproject;
* `ant build-rest-playground`: build the Rest Playground subproject;
* `ant build-all`: builds all available subprojects;
* `ant clean`: removes the `build` and `dist` directories;
* `ant zero`: same as `clean`, but also removes the `cache` directory with all downloaded tools;
* `ant configure`: rebuild the library and tools cache.

== Key Directories and Files

Important directories to be aware of:

* `cache` - stores the downloaded jars, custom tasks and other tools;
* `stage` - the local Apache Karaf installation built to test the subprojects.

The `configure.xml` file contains all the macros and targets used by the subprojects and it's worth looking. It can be used standalone on another projects.

== Installing Java on Raspberry Pi

Raspberry Pi have a fully certified OpenJDK distribution available: https://www.azul.com/products/zulu-embedded/[Zulu® Embedded^], built by https://www.azul.com/[Azul Systems^]. You can install it on Raspbian Stretch using:

....
# apt-get install dirmngr
# apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x219BD9C9
# echo 'deb http://repos.azulsystems.com/debian stable main' > /etc/apt/sources.list.d/zulu.list
# apt-get update
# apt-get install zulu-embedded-8
# java -version
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)
....

== Important Resources

If you need further information, please refer to the following resources:

* http://njbartlett.name/osgibook.html[OSGi in Practice^]: Free, Creative Commons-licensed book on OSGi by Neil Bartlett.
* https://www.osgi.org/developer/resources/learning-resources-tutorials/tutorial-archive/[Tutorial Archive from OSGi Alliance^]: Lots of great articles and resources.
* http://bndtools.org/[BND Tools^]: The standard OSGi tool to build artifacts.
* https://www.osgi.org/developer/specifications/[OSGi Specifications^]: All OSGi specifications available from OSGi Alliance.
* https://www.osgi.org/osgi-release-5-javadoc/[OSGi Release 5 Javadoc^]: Browse online the javadocs for OSGi R5 APIs.

== Copyright

This work is licensed under a http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0].
