= Architecture Examples
// Copyright 2017 NEOautus Ltd. (http://neoautus.com)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

This is the source code for the architectural examples cited on https://github.com/neoautus/lucidj-docs/blob/master/docs/README.adoc[LucidJ Documentation].

Every subdirectory have it's own `build.xml` and can be built independently.

== Prerequisites for Building

* Ant (minimun Ant 1.8.0)

== Building the Examples

By default, Ant will download and cache all needed tools, then invoke the `build-all` target. The output of all builds will be located in `dist` directory.

For details on building the code, see `ant -p`.

These are the available targets:

* `ant build-all`: builds all available versions;
* `ant clean`: removes the `build` and `dist` directories;
* `ant zero`: same as `clean`, but also removes the `cache` directory with all downloaded tools.

== Key Directories

Key directories to be aware of:

* `cache` - stores the downloaded jars for the custom tasks and other tools
* `dist` - the generated artifacts, where:

== Installing Java on Raspberry Pi

Raspberry Pi have a fully certified OpenJDK distribution available: https://www.azul.com/products/zulu-embedded/[Zulu® Embedded^], built by https://www.azul.com/[Azul Systems^]. You can install it on Raspbian Stretch using:

....
# apt-get install dirmngr
# apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0x219BD9C9
# echo 'deb http://repos.azulsystems.com/debian stable main' > /etc/apt/sources.list.d/zulu.list
# apt-get update
# apt-get install zulu-embedded-8
# java -version
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)
....

== Important Resources

If you need further information, please refer to the following resources:

* http://njbartlett.name/osgibook.html[OSGi in Practice^]: Free, Creative Commons-licensed book on OSGi by Neil Bartlett.
* https://www.osgi.org/developer/resources/learning-resources-tutorials/tutorial-archive/[Tutorial Archive from OSGi Alliance^]: Lots of great articles and resources.
* http://bndtools.org/[BND Tools^]: The standard OSGi tool to build artifacts.
* https://www.osgi.org/developer/specifications/[OSGi Specifications^]: All OSGi specifications available from OSGi Alliance.
* https://www.osgi.org/osgi-release-5-javadoc/[OSGi Release 5 Javadoc^]: Browse online the javadocs for OSGi R5 APIs.

== Copyright

This work is licensed under a http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0].
