= Private Libraries
// Copyright 2017 NEOautus Ltd. (http://neoautus.com)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

=== Keeping Jars Private

The OSGi specification allows a fine grained control of what packages are visible or requested, using special Manifest properties. Sometimes, however, we don't have a compliant library. We have just a plain, regular Jar file. What to do? We have 2 options:

. Wrap the Jar, like http://bnd.bndtools.org/chapters/390-wrapping.html[Wrapping Libraries to OSGi Bundles] describes;
. Use a *Private Classpath*, with the rogue Jar contained inside.

=== Example Description

This example uses the famous BouncyCastle security library. _For didactic purposes, we are ignoring that BouncyCastle is fully OSGi-aware, and we're treating it like a plain Jar library._ We build two services, BouncyCastle-1 and BouncyCastle-2, each using a *different version of BouncyCastle* inside it's own *private classpath*.

=== Building

If you want to use the integrated Karaf, you can follow https://github.com/neoautus/architecture-examples/tree/master/00-stage-karaf[these instructions to build the Karaf stage].

* Run `ant build-private-libraries` from the example root;
+
or

* Run `ant` from the subproject directory.

=== Testing

To test OSGi code you need to _deploy_ the test bundles. It's quite similar to a JEE application: the OSGi container runs a collection of other modules, so the test code will _interact_ with these modules instead of simply running like "java -jar Test.jar". Messages from the test modules will appear on the log.

It is recommended to have a _stage_ available (see <<Building>>). If you have, the deployment is _automatic_.

* After building, if you are using the provided Karaf stage, the bundles are already copied into `deploy` directory and are ready to be deployed. If Karaf is running, they are *already deployed*;
* If you wish to test on another systems, the Jars you need are available in `02-private-libraries/dist` directory;

You will see the log messages below:

....
$ tail -f stage/data/log/karaf.log
(...) Currently we have 2 registered security libraries
(...) Library #0: org.lucidj.bouncycastle.BouncyCastle2@xxxxxxxx info=BouncyCastle Security Provider v1.59
(...) Library #1: org.lucidj.bouncycastle.BouncyCastle1@yyyyyyyy info=BouncyCastle Security Provider v1.54
(...) Validate: Hello!
....

=== Explanation

We have two complete, different versions of BouncyCastle: version 1.54 and version 1.59. _They are only visible inside the bundles where they belong_, inside their private classpath. Also, notice while BouncyCastle-1 uses the library classes directly, BouncyCastle-2 uses it through JCE Provider, just as example.

As expected, both services are running together without any hitch.

TIP: This example also demonstrates proper OSGi service usage, with the services implementing a common _interface_.

== Copyright

This work is licensed under a http://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0].
